import { ReactNode } from "react";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} scrollbar-thin scrollbar-thumb-primaryBlue scrollbar-track-primaryGray scrollbar-thumb-rounded-md`}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
